name: Compilar APK de Kivy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Redireccionar codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias del sistema y Dos2Unix
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev libsqlite3-dev dos2unix
        sudo apt-get install -y openjdk-17-jdk unzip zip

    - name: Instalar Buildozer y Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv kivy

    - name: Limpiar saltos de linea de Windows (Dos2Unix)
      run: |
        dos2unix buildozer.spec
        dos2unix main.py

    - name: Ajustar archivo spec automaticamente
      run: |
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/android.api = 33/android.api = 33/' buildozer.spec
        # Forzar una sola arquitectura para evitar el Error Code 1
        sed -i 's/android.archs =.*/android.archs = arm64-v8a/' buildozer.spec

    - name: Compilar con Buildozer
      run: |
        buildozer -v android debug
      continue-on-error: false

    - name: Subir APK Generado
      uses: actions/upload-artifact@v4
      with:
        name: Calculadora-APK
        path: bin/*.apk
